api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: MONEY TRANSFER API PLATFORM
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKeys:
                name: X-AUTH-TOKEN
                type: header

    collection:
        pagination:
            items_per_page: 10
            client_items_per_page: true
