#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
  #resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  #prefix: /admin
  #type: annotation
  entities:
    - App\Entity\User
    - App\Entity\Roles
    - App\Entity\Partner
    - App\Entity\PartnerAccount
    - App\Entity\Deposit
    - App\Entity\Affectation
    - App\Entity\Contract


